full review pre-trial 03
epiverse-trace/tutorials-late pull request #19
Opened 2024-04-18 19:43 UTC by avallecam

This PR aims to collect edit suggestions before trial 03.

Rendered website: https://epiverse-trace.github.io/tutorials-late/

We encourage in-line specific changes in the files changed tab (read [GitHub how-to guide steps 5 to 7](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request))

2024-04-22 10:40 UTC, Degoot-AM requested changes

2024-04-22 10:40 UTC, Degoot-AM commented on episodes/modelling-interventions.Rmd
> +  annotate(
```suggestion
  ggplot2::annotate(
```

2024-04-22 10:40 UTC, Degoot-AM commented on episodes/modelling-interventions.Rmd
> +  aes(
```suggestion
  ggplot2::aes(
```

2024-04-22 10:40 UTC, Degoot-AM commented on episodes/modelling-interventions.Rmd
> +  stat_summary(
```suggestion
  ggplot2::stat_summary(
```

2024-04-22 10:40 UTC, Degoot-AM commented on episodes/modelling-interventions.Rmd
> +  scale_y_continuous(
```suggestion
  ggplot2::scale_y_continuous(
```

2024-04-22 10:40 UTC, Degoot-AM commented on episodes/modelling-interventions.Rmd
> +  labs(
```suggestion
  ggplot2::labs(
```

2024-04-22 10:40 UTC, Degoot-AM commented on episodes/modelling-interventions.Rmd
> +  theme_bw(
```suggestion
  ggplot2::theme_bw(
```

2024-04-22 10:40 UTC, Degoot-AM commented on episodes/modelling-interventions.Rmd
> +  geom_vline(
```suggestion
  ggplot2::geom_vline(
```

2024-04-22 10:40 UTC, Degoot-AM commented on episodes/modelling-interventions.Rmd
> +There are two intervention types for `model_default()`. Rate interventions on model parameters (`transmission_rate` $\beta$, `infectiousness_rate` $\sigma$ and `recovery_rate` $\gamma$) and contact m
```suggestion
There are two intervention types for `model_default()`. Rate interventions on model parameters (`transmission_rate` $\beta$, `infectiousness_rate` $\sigma$ and `recovery_rate` $\gamma$) and contact matrix reductions (`contacts`).
```

2024-04-22 10:40 UTC, Degoot-AM commented on episodes/modelling-interventions.Rmd
> +To implement both contact and rate interventions in the same simulation they must be passed as a list e.g. `intervention = list(transmission_rate = mask_mandate, contacts = close_schools)`. But if th
```suggestion
To implement both contact and rate interventions in the same simulation they must be passed as a list, e.g., `intervention = list(transmission_rate = mask_mandate, contacts = close_schools)`. But if there are multiple interventions that target contact rates, these must be passed as one `contacts` input. See the [vignette on modelling overlapping interventions](https://epiverse-trace.github.io/epidemics/articles/multiple_interventions.html) for more detail. 
```

2024-04-22 10:40 UTC, Degoot-AM commented on episodes/modelling-interventions.Rmd
> +Pharmaceutical interventions (PIs) are measures such as vaccination and mass treatment programs. In the previous section, we assumed that interventions reduced the value of parameter values while the
```suggestion
Pharmaceutical interventions (PIs) are measures such as vaccination and mass treatment programs. In the previous section, we integrated the interventions into the model by reducing  parameter values during specific period of time window in which these intervention set to take place. In the case of vaccination, we assume that after the intervention individuals are no longer susceptible and should be classified into a different disease state. Therefore, we specify the rate at which individuals are vaccinated and track the number of vaccinated individuals over time. 
```

2024-04-22 10:40 UTC, Degoot-AM commented on episodes/modelling-interventions.Rmd
> +Individuals are vaccinated at an age group ($i$) specific time dependent ($t$) vaccination rate ($\nu_{i,t}$). The SEIR components of these equations are described in the tutorial [simulating transmi
```suggestion
Individuals in age group ($i$)  at specific time dependent ($t$)  are vaccinated at rate ($\nu_{i,t}$). The other SEIR components of these equations are described in the tutorial [simulating transmission](../episodes/simulating-transmission.md#simulating-disease-spread). 
```

2024-04-22 10:40 UTC, Degoot-AM commented on episodes/modelling-interventions.Rmd
> +To explore the effect of vaccination we need to create a vaccination object to pass as an input into `model_default()` that includes an age groups specific vaccination rate `nu` and age group specifi
```suggestion
To explore the effect of vaccination we need to create a vaccination object to pass as an input into `model_default()` that includes  age groups specific vaccination rate `nu` and age groups specific start and end times of the vaccination program (`time_begin` and `time_end`). 
```

2024-04-22 10:40 UTC, Degoot-AM commented on episodes/modelling-interventions.Rmd
> +Here we will assume all age groups are vaccinated at the same rate 0.01 and that the vaccination program starts on day 40 and is in place for 150 days.
```suggestion
Here we will assume all age groups are vaccinated at the same rate 0.01 and that the vaccination program starts on day 40 and continue to be in place for 150 days.
```

2024-04-22 10:40 UTC, Degoot-AM commented on episodes/modelling-interventions.Rmd
> +vaccinate <- vaccination(
```suggestion
vaccinate <- epidemics::vaccination(
```

2024-04-22 10:40 UTC, Degoot-AM commented on episodes/modelling-interventions.Rmd
> +output_vaccinate <- model_default(
```suggestion
output_vaccinate <- epidemics::model_default(
```

2024-04-22 10:40 UTC, Degoot-AM commented on episodes/modelling-interventions.Rmd
> +We pass our vaccination object using `vaccination = vaccinate`:
```suggestion
We pass our vaccination object into the model using argument `vaccination = vaccinate`:
```

2024-04-22 10:40 UTC, Degoot-AM commented on episodes/modelling-interventions.Rmd
> +ggplot(data = output[output$compartment == "infectious", ]) +
```suggestion
ggplot2::ggplot(data = output[output$compartment == "infectious", ]) +
```

2024-04-22 10:40 UTC, Degoot-AM commented on episodes/modelling-interventions.Rmd
> +  aes(
```suggestion
  ggplot2::aes(
```

2024-04-22 10:40 UTC, Degoot-AM commented on episodes/modelling-interventions.Rmd
> +  stat_summary(
```suggestion
  ggplot2::stat_summary(
```

2024-04-22 10:40 UTC, Degoot-AM commented on episodes/modelling-interventions.Rmd
> +  scale_y_continuous(
```suggestion
  ggplot2::scale_y_continuous(
```

2024-04-22 10:40 UTC, Degoot-AM commented on episodes/modelling-interventions.Rmd
> +  labs(
```suggestion
  ggplot2::labs(
```

2024-04-22 10:40 UTC, Degoot-AM commented on episodes/modelling-interventions.Rmd
> +  theme_bw(
```suggestion
  ggplot2::theme_bw(
```

2024-04-22 10:40 UTC, Degoot-AM commented on episodes/modelling-interventions.Rmd
> +Different types of intervention can be implemented using mathematical modelling. Modelling interventions requires assumptions of which model parameters are affected (e.g. contact matrices, transmissi
```suggestion
Different types of intervention can be implemented using mathematical modelling. Modelling interventions requires assumptions of which model parameters are affected (e.g. contact matrices, transmission rate), and by what magnitude  and what times in the simulation of an outbreak. 
```

2024-04-22 10:56 UTC, Degoot-AM commented
@avallecam, I enjoyed reading this tutorials and suggest a number of changes to be made. Below are my general remarks:

-   My review did not include the `comparing scenario` as it yet to be completed. 
-  I found this tutorial a bit lengthy, you may consider breaking it down
-  Fail to generate the in-fly transmission diagrams embedded with episodes locally in machine using the workbench framework. I got the following error message `Error in (function (url = NULL, file = "webshot.png", vwidth = 992, vheight = 744, : webshot.js returned failure value: 1`. I do not  know whether this a general problem or specific to my machine, but is worth to check it out. 
-  Use `tracetheme` package in the making the graphs.
- Link the tutorials together to provide a smooth order to flaw.

2024-04-22 11:15 UTC, avallecam commented on episodes/simulating-transmission.Rmd
> +uk_population <- population(
appropriate edit suggestion!

2024-04-22 11:50 UTC, avallecam reviewed
the term preinfectious is used across the episodes. Is there a preference to use `preinfectious` over `latent` period?

2024-04-22 11:50 UTC, avallecam commented on episodes/simulating-transmission.Rmd
> +```
```suggestion
To create our population object, from the {epidemics} package we call the function `population()` specifying a name, the contact matrix, the demography vector and the initial conditions.

```{r population}
uk_population <- epidemics::population(
  name = "UK",
  contact_matrix = contact_matrix,
  demography_vector = demography_vector,
  initial_conditions = initial_conditions
)
```
```

2024-04-22 11:50 UTC, avallecam commented on episodes/simulating-transmission.Rmd
> +We will simulate a strain of influenza with pandemic potential with $R_0=1.46$, a preinfectious period of 3 days and infectious period of 7 days. Therefore our inputs will be:
Which one is clearer? `latent` period or `preinfectious` period?

```suggestion
We will simulate a strain of influenza with pandemic potential with $R_0=1.46$, a preinfectious period of 3 days and infectious period of 7 days.

- `latent_period <- 3.0`
- `infectious_period <- 7.0`
- `basic_reproduction <- 1.46`

Therefore our inputs will be:
```

2024-04-22 11:50 UTC, avallecam commented on episodes/simulating-transmission.Rmd
> +- `recovery_rate = 1.0 / 7.0`.
For consisteny with the callout box bellow

```suggestion
- `infectiousness_rate = 1/latent_period`,
- `recovery_rate = 1/infectious_period`,
- `transmission_rate =  basic_reproduction*recovery_rate`.
```

2024-04-22 11:50 UTC, avallecam commented on episodes/simulating-transmission.Rmd
> +filter(output_plot, compartment %in% c("exposed", "infectious")) %>%
```suggestion
library(tidyverse)

filter(output, compartment %in% c("exposed", "infectious")) %>%
```

2024-04-25 01:58 UTC, avallecam reviewed
brief link edits

2024-04-25 02:01 UTC, avallecam commented on episodes/modelling-interventions.Rmd
> +To implement both contact and rate interventions in the same simulation they must be passed as a list, e.g., `intervention = list(transmission_rate = mask_mandate, contacts = close_schools)`. But if
```suggestion
To implement both contact and rate interventions in the same simulation they must be passed as a list, e.g., `intervention = list(transmission_rate = mask_mandate, contacts = close_schools)`. But if there are multiple interventions that target contact rates, these must be passed as one `contacts` input. See the [vignette on modelling overlapping interventions](https://epiverse-trace.github.io/epidemics/articles/modelling_multiple_interventions.html) for more detail. 
```

2024-04-25 03:43 UTC, avallecam commented
closing as redirected to main in #29

2024-04-25 03:43 UTC, closed without merging