adding .Tex version of hands-out file
epiverse-trace/tutorials-late pull request #56
Opened 2024-10-28 11:21 UTC by Degoot-AM

This PR adds `.Tex` version of hands-out file for better edit suggestions and reveiw.

2024-11-19 19:22 UTC, avallecam requested changes
Thanks @Degoot-AM for working on this! This totally fits the aims of the session to assess the concepts learned before working in code.

I added some minor edits to increase the space length as some responses are expected to write more words. 

I proposed two major addition: 

- Add some paragraphs about rates and how they are calculated from time period. Also, pasted adapted paragraphs to lead learners read how the R0 is related with beta and gamma.

- List of parameters as sentences, and table of parameters to fill. This practical aims to write by hand the numbers before working on code in the next session.

2024-11-19 19:22 UTC, avallecam commented on learners/files/hands-on.tex
> +\section{Equations}\label{eqs}
```suggestion
Model parameters are often (but not always) specified as rates.
The rate at which an event occurs is the inverse of the average time until that event.
For example, in the SEIR model, the recovery rate $\gamma$ is the inverse of the average infectious period.\\

Values of these rates can be determined from the natural history of the disease.
For example,  if people are on average infectious for 8 days, then in the model, 
1/8 of currently infectious people would recover each day
(i.e. the rate of recovery, $\gamma=1/8=0.125$).

\section{Equations}\label{eqs}
```

2024-11-19 19:22 UTC, avallecam commented on learners/files/hands-on.tex
> +  is the contact rate, defined as the average number of contacts per unit of time.
```suggestion
  is the contact rate, defined as the average number of contacts per unit of time.\\
```

2024-11-19 19:22 UTC, avallecam commented on learners/files/hands-on.tex
> +a simple SEIR framework for infectious disease outbreaks.
```suggestion
a simple SEIR framework for infectious disease outbreaks.\\
```

2024-11-20 21:03 UTC, Degoot-AM commented
> Thanks @Degoot-AM for working on this! This totally fits the aims of the session to assess the concepts learned before working in code.
> 
> I added some minor edits to increase the space length as some responses are expected to write more words.
> 
> I proposed two major addition:
> 
>     * Add some paragraphs about rates and how they are calculated from time period. Also, pasted adapted paragraphs to lead learners read how the R0 is related with beta and gamma.
> 
>     * List of parameters as sentences, and table of parameters to fill. This practical aims to write by hand the numbers before working on code in the next session.

Thank you @avallecam for your valuable comments

2024-11-20 21:07 UTC, merged