add episode on vaccine strategies
epiverse-trace/tutorials-late pull request #73
Opened 2024-12-20 10:07 UTC by amanda-minter

This pull request adds an episode on vaccine strategies as proposed in #54

2025-01-07 07:24 UTC, adamkucharski requested changes
Thanks for putting this together, it's really useful to have this additional. Have added a few comments, mostly around clarity of interpretation for learners.

2025-01-07 07:24 UTC, adamkucharski commented on episodes/vaccine-comparisons.Rmd
> ++ `data` : the model output,
Beyond scope of this specific PR, but wonder if it's unclear to learners to have epidemics models generate an output labelled 'data' for simulations?

2025-01-07 07:24 UTC, adamkucharski commented on episodes/vaccine-comparisons.Rmd
> +  )
Would it be useful to also output a quick table comparing cumulative infections under each scenario?

2025-01-07 07:24 UTC, adamkucharski commented on episodes/vaccine-comparisons.Rmd
> +The contact matrix for our example is :
Reiterate it's the same matrix as one loaded above?

2025-01-07 07:24 UTC, adamkucharski commented on episodes/vaccine-comparisons.Rmd
> ++ vaccinating each age group at a rate 0.001,
```suggestion
+ vaccinating all age groups at a rate 0.001,
```

2025-01-07 07:24 UTC, adamkucharski commented on episodes/vaccine-comparisons.Rmd
> +  )
As above, a table with cumulative infections here would be useful to show overall differences

2025-01-07 07:24 UTC, adamkucharski commented on episodes/vaccine-comparisons.Rmd
> +Vaccinating group 3 only results in the highest epidemic peak size. Targeting group 2 results in the smallest epidemic peak size. Whereas targeting all age groups pushes the epidemic peak time later.
Would it be useful to have a short subsection after this one that implements an age specific infection-fatality-risk? E.g. take the age-stratified cumulative infections for each scenario, then scale by age-specific risk? This could be a nice challenge to show that targeting younger groups can reduce impact of infections that have higher IFR for elderly?

2025-01-07 07:24 UTC, adamkucharski commented on episodes/vaccine-comparisons.Rmd
> +The NPI we will consider is closing schools. Specifically, a school closure that will reduce the contacts between school aged children (aged 0-15) by 0.5, and will cause a small reduction (0.01) in t
```suggestion
The NPI we will consider is temporarily closing schools. Specifically, a school closure that will reduce the contacts between school aged children (aged 0-15) by 0.5, and will cause a small reduction (0.01) in the contacts between adults (aged 15 and over). For the vaccine program, we assume an equal vaccination rate of 0.01 in each age group.
```
Maybe add a citation for school closures, which is common proposed measure for pandemic flu - and sometimes seasonal flu also: https://pmc.ncbi.nlm.nih.gov/articles/PMC2609897/. The damage of closures for COVID is likely to make school closure unappealing as policy option for future pandemic, but for a severe infection among younger groups, would likely end up on the cards (whether explicitly or by default, via behaviour change).

2025-01-07 07:24 UTC, adamkucharski commented on episodes/vaccine-comparisons.Rmd
> +We define **early implementation** as the first day of the simulation, and **late implementation** as 50 days after the start of the simulation. We assume the control measures are in place for 100 da
Maybe say 'first day of the simulation (i.e. when there are X infections in total)'? And similar for 50 days - as this is closer to the sort of triggers that would be used in real-life?

2025-01-07 07:24 UTC, adamkucharski commented on episodes/vaccine-comparisons.Rmd
> +Vaccinating group 3 only results in the highest epidemic peak size. Targeting group 2 results in the smallest epidemic peak size. Whereas targeting all age groups pushes the epidemic peak time later.
Worth briefly mentioning (either here or referencing elsewhere if already covered in another episode) that we're often interested in both the peak size (i.e. healthcare pressure at single point in time) as well as overall epidemic size (i.e. cumulative disease)?

2025-01-07 07:24 UTC, adamkucharski commented on episodes/vaccine-comparisons.Rmd
> +Early implementation of NPIs (`early npi`) shifts the timing of the peak of infectious individuals but does not decrease the magnitude by much. Early implementation of the vaccine (`early vacc`) is t
```suggestion
Early implementation of NPIs (`early npi`) delays the timing of the peak of infectious individuals but does not decrease the magnitude by much once the measure is lifted. Early implementation of the vaccine (`early vacc`) is the most effective control for reducing the peak number of infectious individuals, because it reduces the size of the susceptible group rather than just temporarily keeping infections away from it. Having an NPI in place before the vaccine is implemented (`early npi, late vacc`) is more effective than simply just implementing the vaccine late (`late vacc`).
```

2025-01-07 07:24 UTC, adamkucharski commented on episodes/vaccine-comparisons.Rmd
> +Using model generated disease trajectories we have investigated the potential impact of different vaccination strategies. When infection has group specific risk, targeted vaccination programs may be
```suggestion
Using model generated disease trajectories we have investigated the potential impact of different vaccination strategies. When infection has group specific risk, targeted vaccination programs may be more effective in reducing epidemic peak. NPIs can be used alongside vaccine development to delay epidemic peaks before vaccines are readily available. 
```

2025-01-07 07:24 UTC, adamkucharski commented on episodes/vaccine-comparisons.Rmd
> +In this tutorial we have investigated the potential effect of infection blocking vaccines, but we can use models to explore other effects of vaccines including imperfect vaccines. The disease traject
Worth adding some suggested further reading for DALYs – especially if above subsection on age-specific deaths included, as could give a sentence of intuition here.

2025-01-07 07:24 UTC, adamkucharski commented on episodes/vaccine-comparisons.Rmd
> +- Herd immunity is a indirect effect of vaccination programs
Probably beyond scope of this episode to model, but could get them to think about the impact vaccination would have if it came very late in the epidemic (i.e. after post-infection immunity had accumulated) – this happened in 2009, for example: https://pubmed.ncbi.nlm.nih.gov/20096762/

2025-01-13 09:19 UTC, amanda-minter commented on episodes/vaccine-comparisons.Rmd
> ++ vaccination program 01 : vaccination rate 0.001
I believe it is the proportion of those susceptible, [see here](
https://github.com/epiverse-trace/epidemics/blob/f706261bac19282e813ca43675ff16dcb79b3d40/R/model_default.R#L343C11-L343C21)

2025-01-23 13:23 UTC, amanda-minter commented on episodes/vaccine-comparisons.Rmd
> +In this tutorial we have investigated the potential effect of infection blocking vaccines, but we can use models to explore other effects of vaccines including imperfect vaccines. The disease traject
Added DALYs to the glossary with a link to further reading

2025-01-24 11:09 UTC, amanda-minter commented on episodes/vaccine-comparisons.Rmd
> +Vaccinating group 3 only results in the highest epidemic peak size. Targeting group 2 results in the smallest epidemic peak size. Whereas targeting all age groups pushes the epidemic peak time later.
I've added a short section on this using the same contact matrix as before. The example does show that vaccinating other age groups has an effect on deaths in the eldest group, but not the youngest age group. The example could be updated with a different contact matrix to illustrate that point more heavily if wanted.

2025-01-29 17:25 UTC, adamkucharski commented on episodes/vaccine-comparisons.Rmd
> +Vaccinating group 3 only results in the highest epidemic peak size. Targeting group 2 results in the smallest epidemic peak size. Whereas targeting all age groups pushes the epidemic peak time later.
Thanks, looks good to me

2025-02-03 12:52 UTC, avallecam approved these changes
rebased and ready to be merged 🚀

2025-02-03 12:52 UTC, merged